services:
  postgres:
    image: postgres:16
    container_name: school-db
    restart: always
    environment:
      POSTGRES_USER: school_user
      POSTGRES_PASSWORD: school_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U school_user -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - micro-net
    volumes:
      - school-db-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  keycloak:
    container_name: keycloak_demo
    image: quay.io/keycloak/keycloak:25.0.5
    ports:
      - '9090:8080'
    command: start-dev --import-realm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: school_user
      KC_DB_PASSWORD: school_pass
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./configs/dnevnik-realm-realm.json:/opt/keycloak/data/import/realm.json:ro

    networks:
      - micro-net
    depends_on:
      postgres:
        condition: service_healthy

  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./configs/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - micro-net

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - loki
    networks:
      - micro-net

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    volumes:
      - ./configs/alloy-config.alloy:/etc/alloy/config.alloy
      - ./logs:/logs
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    networks:
      - micro-net
    depends_on:
      - loki

  eureka-server:
    build:
      context: ./backend
      dockerfile: ./eureka-server/Dockerfile
    container_name: eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "8761:8761"
    networks:
      - micro-net

  api-gateway:
    build:
      context: ./backend
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - KC_URL=http://keycloak:8080
      - KC_REALM=dnevnik-realm
      - EUREKA_URL=http://eureka-server:8761
      - APP_NAME=api-gateway
    volumes:
      - ./logs/api-gateway:/app/logs
    networks:
      - micro-net

  user-service:
    build:
      context: ./backend
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    ports:
      - "9001:9001"
    depends_on:
      - eureka-server
      - postgres
      - keycloak
    environment:
      - KC_URL=http://keycloak:8080
      - KC_REALM=dnevnik-realm
      - KC_CLIENT_SECRET=iz0AGFzsa5d05DhxdoQphGGkcPXCRlEV
      - PSQL_URL=jdbc:postgresql://postgres:5432
      - PSQL_USER_DB=user_db
      - PSQL_USER_USERNAME=school_user
      - PSQL_USER_PASSWORD=school_pass
      - LOKI_URL=http://loki:3100
      - EUREKA_URL=http://eureka-server:8761
      - APP_NAME=user-service
    volumes:
      - ./logs/user-service:/app/logs
    networks:
      - micro-net

  academic-service:
    build:
      context: ./backend
      dockerfile: ./academic-service/Dockerfile
    container_name: academic-service
    ports:
      - "9002:9002"
    depends_on:
      - eureka-server
      - postgres
      - keycloak
    environment:
      - KC_URL=http://keycloak:8080
      - KC_REALM=dnevnik-realm
      - KC_CLIENT_SECRET=iz0AGFzsa5d05DhxdoQphGGkcPXCRlEV
      - PSQL_URL=jdbc:postgresql://postgres:5432
      - PSQL_ACADEMIC_DB=academic_db
      - PSQL_ACADEMIC_USERNAME=school_user
      - PSQL_ACADEMIC_PASSWORD=school_pass
      - LOKI_URL=http://loki:3100
      - EUREKA_URL=http://eureka-server:8761
      - APP_NAME=academic-service
      # - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./logs/academic-service:/app/logs
    networks:
      - micro-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - VITE_APP_NAME=dnevnik-frontend
      - VITE_BACKEND_URL=http://localhost:8080
    ports:
      - "5173:80"

volumes:
  school-db-data:
  keycloak_data:
  loki-data:
  grafana-data:

networks:
  micro-net:
    driver: bridge