create sequence attendance_seq start with 1 increment by 50;
create sequence grade_constant_seq start with 1 increment by 50;
create sequence grade_seq start with 1 increment by 50;
create sequence lesson_seq start with 1 increment by 50;
create sequence school_classes_seq start with 1 increment by 50;
create sequence subject_seq start with 1 increment by 50;
create sequence teaching_assignment_seq start with 1 increment by 50;
create table attendance (id bigint not null, lesson_id_id bigint, student_id bigint, status varchar(255) check (status in ('PRESENT','ABSENT','LATE','EXCUSED')), primary key (id));
create table grade (value integer, created_at timestamp(6), id bigint not null, lesson_id bigint, student_id bigint, updated_at timestamp(6), type varchar(255), primary key (id));
create table grade_constant (value integer, id bigint not null, description varchar(255), name varchar(255), primary key (id));
create table lesson (lesson_number integer, id bigint not null, teaching_assignment_id bigint, class_room varchar(255), day_of_week varchar(255) check (day_of_week in ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')), primary key (id));
create table lesson_attendances (attendances_id bigint not null unique, lesson_id bigint not null);
create table lesson_grades (grades_id bigint not null unique, lesson_id bigint not null);
create table school_classes (class_teacher_id bigint, created_at timestamp(6), id bigint not null, updated_at timestamp(6), name varchar(255), year varchar(255), primary key (id));
create table school_classes_lessons (lessons_id bigint not null unique, school_class_id bigint not null);
create table subject (created_at timestamp(6), id bigint not null, updated_at timestamp(6), name varchar(255) not null, primary key (id));
create table teaching_assignment (id bigint not null, school_class_id bigint, subject_id bigint, teacher_id bigint, primary key (id));
alter table if exists attendance add constraint FKj9egiirkhker7lmvkcntn338v foreign key (lesson_id_id) references lesson;
alter table if exists grade add constraint FK65by7eln3rv98qrechgx4rvgv foreign key (lesson_id) references lesson;
alter table if exists lesson add constraint FKir43im05uqyjgvyy2j1pt6uk1 foreign key (teaching_assignment_id) references teaching_assignment;
alter table if exists lesson_attendances add constraint FKcnmpfec3m9gp5ilutqjum322s foreign key (attendances_id) references attendance;
alter table if exists lesson_attendances add constraint FKqlvshxedmou0nbxf3r24bjrhg foreign key (lesson_id) references lesson;
alter table if exists lesson_grades add constraint FK7wc6r5mo7dcd61n02unsu5uct foreign key (grades_id) references grade;
alter table if exists lesson_grades add constraint FK8u9r0g4cmlxlxuiis3hknh64x foreign key (lesson_id) references lesson;
alter table if exists school_classes_lessons add constraint FK9c9peofc9bti89gy2n02iuype foreign key (lessons_id) references lesson;
alter table if exists school_classes_lessons add constraint FK1hyyd3lhvll9u8gcf1v03ff7c foreign key (school_class_id) references school_classes;
alter table if exists teaching_assignment add constraint FKo6qsj6is5wdy3kn5fwr6dwta3 foreign key (school_class_id) references school_classes;
alter table if exists teaching_assignment add constraint FKeo8hv8bv0fc7fxbkkkej0cd26 foreign key (subject_id) references subject;
create sequence attendance_seq start with 1 increment by 50;
create sequence grade_constant_seq start with 1 increment by 50;
create sequence grade_seq start with 1 increment by 50;
create sequence lesson_seq start with 1 increment by 50;
create sequence school_classes_seq start with 1 increment by 50;
create sequence subject_seq start with 1 increment by 50;
create sequence teaching_assignment_seq start with 1 increment by 50;
create table attendance (id bigint not null, lesson_id_id bigint, student_id bigint, status varchar(255) check (status in ('PRESENT','ABSENT','LATE','EXCUSED')), primary key (id));
create table grade (value integer, created_at timestamp(6), id bigint not null, lesson_id bigint, student_id bigint, updated_at timestamp(6), type varchar(255), primary key (id));
create table grade_constant (value integer, id bigint not null, description varchar(255), name varchar(255), primary key (id));
create table lesson (lesson_number integer, id bigint not null, teaching_assignment_id bigint, class_room varchar(255), day_of_week varchar(255) check (day_of_week in ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')), primary key (id));
create table lesson_attendances (attendances_id bigint not null unique, lesson_id bigint not null);
create table lesson_grades (grades_id bigint not null unique, lesson_id bigint not null);
create table school_classes (class_teacher_id bigint, created_at timestamp(6), id bigint not null, updated_at timestamp(6), name varchar(255), year varchar(255), primary key (id));
create table school_classes_lessons (lessons_id bigint not null unique, school_class_id bigint not null);
create table subject (created_at timestamp(6), id bigint not null, updated_at timestamp(6), name varchar(255) not null, primary key (id));
create table teaching_assignment (id bigint not null, school_class_id bigint, subject_id bigint, teacher_id bigint, primary key (id));
alter table if exists attendance add constraint FKj9egiirkhker7lmvkcntn338v foreign key (lesson_id_id) references lesson;
alter table if exists grade add constraint FK65by7eln3rv98qrechgx4rvgv foreign key (lesson_id) references lesson;
alter table if exists lesson add constraint FKir43im05uqyjgvyy2j1pt6uk1 foreign key (teaching_assignment_id) references teaching_assignment;
alter table if exists lesson_attendances add constraint FKcnmpfec3m9gp5ilutqjum322s foreign key (attendances_id) references attendance;
alter table if exists lesson_attendances add constraint FKqlvshxedmou0nbxf3r24bjrhg foreign key (lesson_id) references lesson;
alter table if exists lesson_grades add constraint FK7wc6r5mo7dcd61n02unsu5uct foreign key (grades_id) references grade;
alter table if exists lesson_grades add constraint FK8u9r0g4cmlxlxuiis3hknh64x foreign key (lesson_id) references lesson;
alter table if exists school_classes_lessons add constraint FK9c9peofc9bti89gy2n02iuype foreign key (lessons_id) references lesson;
alter table if exists school_classes_lessons add constraint FK1hyyd3lhvll9u8gcf1v03ff7c foreign key (school_class_id) references school_classes;
alter table if exists teaching_assignment add constraint FKo6qsj6is5wdy3kn5fwr6dwta3 foreign key (school_class_id) references school_classes;
alter table if exists teaching_assignment add constraint FKeo8hv8bv0fc7fxbkkkej0cd26 foreign key (subject_id) references subject;
