server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: diary-service
          uri: lb://diary-service
          predicates:
            - Path=/diary-service/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
