create table academic_periods
(
    id          bigint generated by default as identity primary key,
    name        varchar(50),
    school_year varchar(50),
    start_date  date,
    end_date    date,
    closed   boolean not null,
    created_at  timestamptz,
    updated_at  timestamptz,
    deleted_at  timestamptz
);

create table school_classes
(
    id               bigint generated by default as identity primary key,
    name             varchar(50),
    year             varchar(50),
    class_teacher_id bigint,
    created_at       timestamptz,
    updated_at       timestamptz,
    deleted_at       timestamptz
);

create table class_students
(
    id              bigint generated by default as identity primary key,
    school_class_id bigint not null
        constraint fk_class_students_school_class
            references school_classes,
    student_id      bigint not null,
    created_at      timestamptz,
    updated_at      timestamptz,
    deleted_at      timestamptz
);

create table subjects
(
    id         bigint generated by default as identity primary key,
    name       varchar(50) not null,
    created_at timestamptz,
    updated_at timestamptz,
    deleted_at timestamptz
);

create table teaching_assignments
(
    id              bigint generated by default as identity primary key,
    school_class_id bigint not null
        constraint fk_teaching_assignment_school_class
            references school_classes,
    subject_id      bigint not null
        constraint fk_teaching_assignment_subject
            references subjects,
    teacher_id      bigint,
    created_at      timestamptz,
    updated_at      timestamptz,
    deleted_at      timestamptz
);

create table schedule_lessons
(
    id                     bigint generated by default as identity primary key,
    teaching_assignment_id bigint       not null
        constraint fk_schedule_lesson_teaching_assignment
            references teaching_assignments,
    day_of_week            varchar(10) not null constraint chk_day_of_week
        check(day_of_week in ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')),
    lesson_number          integer      not null,
    class_room             varchar(50),
    valid_from             date,
    valid_to               date,
    created_at             timestamptz,
    updated_at             timestamptz,
    deleted_at             timestamptz
);

create table lesson_instances
(
    id                 bigint generated by default as identity primary key,
    schedule_lesson_id bigint not null
        constraint fk_lesson_instance_schedule_lesson
            references schedule_lessons,
    lesson_date        date   not null,
    created_at         timestamptz,
    updated_at         timestamptz,
    deleted_at         timestamptz
);

create table period_grades
(
    id                     bigint generated by default as identity primary key,
    student_id             bigint  not null,
    academic_period_id     bigint  not null
        constraint fk_period_grade_academic_period
            references academic_periods,
    teaching_assignment_id bigint  not null
        constraint fk_period_grade_teaching_assignment
            references teaching_assignments,
    value                  integer not null
        constraint period_grades_value_check
            check ((value <= 5) AND (value >= 1)),
    description            varchar(255),
    created_at             timestamptz,
    updated_at             timestamptz,
    deleted_at             timestamptz
);

create table attendances
(
    id                 bigint generated by default as identity primary key,
    student_id         bigint,
    lesson_instance_id bigint constraint fk_attendances_lesson_instance references lesson_instances,
    status             varchar(10) not null constraint chk_attendance_status
                            check (status in ('ABSENT','LATE','EXCUSED')),
    created_at         timestamptz,
    updated_at         timestamptz,
    deleted_at         timestamptz
);

create table grades
(
    id                 bigint generated by default as identity primary key,
    student_id         bigint,
    lesson_instance_id bigint not null
        constraint fk_grade_lesson_instance
            references lesson_instances,
    type               varchar(10) not null constraint chk_grade_type check (type in ('CONTROL','HOMEWORK','TEST')),
    value              integer constraint grades_value_check check ((value <= 5) AND (value >= 1)),
    weight             integer constraint grades_weight_check check (weight >= 1),
    created_at         timestamptz,
    updated_at         timestamptz,
    deleted_at         timestamptz
);

create table homeworks
(
    id                 bigint generated by default as identity primary key,
    lesson_instance_id bigint not null
        constraint fk_homework_lesson_instance
            references lesson_instances,
    text               text   not null,
    created_at         timestamptz,
    updated_at         timestamptz,
    deleted_at         timestamptz
);



create index idx_class_students_school_class_id on class_students (school_class_id);
create index idx_teaching_assignments_school_class_id on teaching_assignments (school_class_id);
create index idx_teaching_assignments_subject_id on teaching_assignments (subject_id);
create index idx_schedule_lessons_teaching_assignment_id on schedule_lessons (teaching_assignment_id);
create index idx_lesson_instances_schedule_lesson_id on lesson_instances (schedule_lesson_id);
create index idx_period_grades_academic_period_id on period_grades (academic_period_id) where deleted_at is null;
create index idx_period_grades_teaching_assignment_id on period_grades (teaching_assignment_id) where deleted_at is null;
create index idx_lesson_instances_lesson_date on lesson_instances (lesson_date) where deleted_at is null;

create index idx_grades_student_id on grades (student_id);
create index idx_attendances_student_id on attendances (student_id);
create index idx_period_grades_student_id on period_grades (student_id) where deleted_at is null;
create index idx_teaching_assignments_teacher_id on teaching_assignments (teacher_id) where deleted_at is null;

create index idx_attendances_lesson_instance_id on attendances (lesson_instance_id);
create index idx_grades_lesson_instance_id on grades (lesson_instance_id);
create index idx_homeworks_lesson_instance_id on homeworks (lesson_instance_id);

create unique index uq_academic_periods_active on academic_periods (school_year, name) where deleted_at is null;
create unique index uq_attendances_active on attendances (student_id, lesson_instance_id) where deleted_at is null;
create unique index uq_lesson_instances_active on lesson_instances (schedule_lesson_id, lesson_date) where deleted_at is null;
create unique index uq_period_grades_active on period_grades (student_id, academic_period_id, teaching_assignment_id) where deleted_at is null;
create unique index uq_schedule_lessons_active on schedule_lessons (teaching_assignment_id, day_of_week, lesson_number) where deleted_at is null;
create unique index uq_teaching_assignments_active on teaching_assignments (teacher_id, school_class_id, subject_id) where deleted_at is null;
create unique index uq_class_students_active on class_students (student_id) where deleted_at is null;