package com.rusobr.user.web.exception;

public enum ExceptionCode {
    PARENT_NOT_FOUND,
    PARENT_PROFILE_DETAILS_CONFLICT,

    TEACHER_NOT_FOUND,
    TEACHER_PROFILE_DETAILS_CONFLICT,

    STUDENT_NOT_FOUND,
    STUDENT_ALREADY_HAS_PARENT,
    STUDENT_HAS_NO_PARENT,
    STUDENT_PROFILE_DETAILS_CONFLICT,

    USER_NOT_FOUND,
    INVALID_USER_ROLE,
    USER_CREATE_CONFLICT,
    USER_UPDATE_CONFLICT,

    USERNAME_ALREADY_EXISTS,

    KEYCLOAK_USER_NOT_FOUND,
    KEYCLOAK_USER_BAD_REQUEST,

    SCHOOL_CLASS_BY_STUDENT_NOT_FOUND,

    ACADEMIC_SERVICE_UNAVAILABLE,
    ACADEMIC_SERVICE_TEACHER_INFO_NOT_FOUND,
    ACADEMIC_SERVICE_UNAUTHORIZED,
    ACADEMIC_SERVICE_FORBIDDEN,

    DB_VALIDATION_ERROR,
    VALIDATION_ERROR,
}
