create table users
(
    id          bigint generated by default as identity primary key,
    username    varchar(50),
    first_name  varchar(50),
    last_name   varchar(50),
    keycloak_id varchar(255) not null,
    created_at  timestamptz,
    updated_at  timestamptz,
    deleted_at  timestamptz
);

create table parents
(
    id         bigint primary key references users(id),
    created_at timestamptz,
    updated_at timestamptz,
    deleted_at timestamptz
);

create table students
(
    id            bigint primary key references users(id),
    parent_id     bigint
        constraint fk_students_parents references parents,
    study_profile varchar(255),
    created_at    timestamptz,
    updated_at    timestamptz,
    deleted_at    timestamptz
);

create table teachers
(
    id           bigint primary key references users(id),
    email        varchar(100),
    phone_number varchar(50),
    created_at   timestamptz,
    updated_at   timestamptz,
    deleted_at   timestamptz
);

create table user_roles
(
    user_id   bigint not null
        constraint fk_user_roles_users references users,
    role_name varchar(50)
        constraint user_roles_role_name_check
            check (role_name in ('ADMIN', 'PARENT', 'STUDENT', 'TEACHER'))
);

create index idx_users_firstname on users (first_name) where deleted_at is null;
create index idx_users_lastname on users (last_name) where deleted_at is null;
create index idx_students_parent_id on students (parent_id) where deleted_at is null;
create index idx_user_roles_user_id on user_roles (user_id);

create unique index uq_users_keycloak_id on users (keycloak_id) where deleted_at is null;
