server:
  port: 9003

spring:
  application:
    name: grade-service
  datasource:
    url: jdbc:postgresql://localhost:5432/school_db
    username: school_user
    password: school_pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

