package com.rusobr.academic.web.exception;

public enum ExceptionCode {
    ACADEMIC_PERIOD_OPEN_CONFLICT,
    ACADEMIC_PERIOD_CLOSE_CONFLICT,
    ACADEMIC_PERIOD_NOT_FOUND,
    ACADEMIC_PERIODS_NOT_FOUND,
    ACADEMIC_PERIOD_ALREADY_EXISTS,
    ACADEMIC_PERIOD_DATES_CONFLICT,
    ACADEMIC_PERIOD_CLOSED_CONFLICT,

    ACADEMIC_YEAR_CLOSED_CONFLICT,
    ACADEMIC_YEAR_NOT_FOUND,
    ACADEMIC_YEAR_DATES_CONFLICT,
    ACADEMIC_YEAR_CLOSE_CONFLICT,
    ACADEMIC_YEAR_OPEN_CONFLICT,

    SCHOOL_CLASS_NOT_FOUND,
    SCHOOL_CLASS_UNIQUE_CONFLICT,
    SCHOOL_CLASS_STUDENT_ALREADY_PRESENT,

    CLASS_STUDENT_NOT_FOUND,

    FINAL_GRADE_YEAR_NOT_CLOSED_CONFLICT,
    FINAL_GRADE_NOT_FOUND,

    GRADE_NOT_FOUND,

    TEACHING_ASSIGNMENT_NOT_FOUND,

    LESSON_INSTANCE_NOT_FOUND,

    PERIOD_GRADE_NOT_FOUND,

    HOMEWORK_NOT_FOUND,

    SCHEDULE_SLOT_ALREADY_TAKEN,
    SCHEDULE_ALREADY_EXIST,
    SCHEDULE_ALREADY_CLOSED,
    SCHEDULE_NOT_FOUND,

    SUBJECT_NOT_FOUND,

    TEACHER_SUBJECT_ALREADY_EXISTS,
    TEACHER_SUBJECT_NOT_FOUND,

    USER_SERVICE_UNAVAILABLE,
    USER_SERVICE_STUDENT_NOT_FOUND,
    USER_SERVICE_TEACHER_NOT_FOUND,
}
