spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: academic-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_URL:http://localhost:9090}/realms/${KC_REALM:dnevnik-realm}
  datasource:
    url: ${PSQL_URL:jdbc:postgresql://localhost:5432}/${PSQL_ACADEMIC_DB:academic_db}
    username: ${PSQL_ACADEMIC_USER:school_user}
    password: ${PSQL_ACADEMIC_PASS:school_pass}
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    path: /v3/api-docs

eureka:
  instance:
    hostname: ${APP_NAME:localhost}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/

logging:
  loki:
    url: ${LOKI_URL:http://localhost:3100}/loki/api/v1/push
  level:
    root: INFO
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      user-service:
        base-config: default

  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

  timelimiter:
    instances:
      user-service:
        timeout-duration: 3s

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,circuitbreakerevents,metrics
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

keycloak:
  url: ${KC_URL:http://localhost:9090}
  realm: ${KC_REALM:dnevnik-realm}

server:
  port: 9002
