spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: academic-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_URL:http://localhost:9090}/realms/${KC_REALM:dnevnik-realm}
  datasource:
    url: ${PSQL_URL:jdbc:postgresql://localhost:5432}/${PSQL_ACADEMIC_DB:academic_db}
    username: ${PSQL_ACADEMIC_USER:school_user}
    password: ${PSQL_ACADEMIC_PASS:school_pass}
    driver-class-name: org.postgresql.Driver
    
springdoc:
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/

logging:
  loki:
    url: ${LOKI_URL:http://localhost:3100}/loki/api/v1/push
  level:
    root: INFO

management:
  tracing:
    sampling:
      probability: 1.0

keycloak:
  url: ${KC_URL:http://localhost:9090}
  realm: ${KC_REALM:dnevnik-realm}

server:
  port: 9002